export const EVENT_TYPES = {
    USER_CREATED: 'USER_CREATED',
    USER_UPDATED: 'USER_UPDATED',
    EVENT_CREATED: 'EVENT_CREATED',
    EVENT_UPDATED: 'EVENT_UPDATED',
    EVENT_DELETED: 'EVENT_DELETED',
    ATTENDANCE_MARKED: 'ATTENDANCE_MARKED',
    ASSESSMENT_CREATED: 'ASSESSMENT_CREATED',
    ASSESSMENT_UPDATED: 'ASSESSMENT_UPDATED',
    ASSESSMENT_DELETED: 'ASSESSMENT_DELETED',
  };
  