apiVersion: apps/v1
kind: Deployment
metadata:
  name: shiksha-reports
  labels:
    app: shiksha-reports

spec:
  replicas: 1

  selector:
    matchLabels:
      app: shiksha-reports

  template:
    metadata:
      labels:
        app: shiksha-reports

    spec:
      terminationGracePeriodSeconds: 0

      containers:
        - name: shiksha-reports
          image: ${ECR_REPOSITORY}:${IMAGE_TAG}
          imagePullPolicy: Always

          ports:
            - containerPort: 4000

          envFrom:
            - configMapRef:
                name: shiksha-reports-service-config

          resources: {}

      restartPolicy: Always

---
apiVersion: v1
kind: Service

metadata:
  name: shiksha-reports

spec:
  type: ClusterIP

  selector:
    app: shiksha-reports

  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
